# This Dockerfile expect that application was previously built with `gradle buildFatJar` command
FROM artifactory.mallgroup.com/docker/openjdk:11
EXPOSE 8080:8080
RUN mkdir /app
COPY ./build/libs/*all.jar /app/ktor-app.jar
ENTRYPOINT ["java","-jar","/app/ktor-app.jar"]